# AND 게이트 만들기

In [1]:
import torch

In [2]:
and_data = torch.tensor([[0,0],
                       [0,1],
                       [1,0],
                       [1,1]], dtype=torch.float32)
and_labels = torch.tensor([[0],
                         [0],
                         [0],
                         [1]], dtype=torch.float32)

In [3]:
import numpy as np
np.random.randn(32,32).shape

(32, 32)

In [4]:
# image_data = [32x32,32x32,32x32]
# label_data = [새, 고양이, 강아지]

In [5]:
# torch.random.rand(16, 224, 224, 3)

In [6]:
import torch.nn as nn

l1 = nn.Linear(2,1)
x = l1(and_data)
# torch.sigmoid(x)
torch.relu(x)

tensor([[0.1261],
        [0.0000],
        [0.1526],
        [0.0000]], grad_fn=<ReluBackward0>)

In [7]:
dir(l1)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_per

In [8]:
l1.weight, l1.bias, l1.parameters

(Parameter containing:
 tensor([[ 0.0265, -0.1915]], requires_grad=True),
 Parameter containing:
 tensor([0.1261], requires_grad=True),
 <bound method Module.parameters of Linear(in_features=2, out_features=1, bias=True)>)

In [9]:
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN,self).__init__()
        self.fc1 = nn.Linear(2,1)

    def forward(self, x):
        # x = torch.view(x, -1)
        x = self.fc1(x)
        x = torch.sigmoid(x)
        return x

In [10]:
model = SimpleNN()
model

SimpleNN(
  (fc1): Linear(in_features=2, out_features=1, bias=True)
)

In [11]:
model(and_data)

tensor([[0.4718],
        [0.5580],
        [0.3492],
        [0.4313]], grad_fn=<SigmoidBackward0>)

In [19]:
loss_fn = nn.BCELoss()

In [20]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=1e-3)

In [21]:
model = SimpleNN()
loss_fn = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

In [22]:
# tf.fit(model, data, loss_fn, optimizer, epoches=100) #텐서플로 방식

In [23]:
# wh
loss_fn = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

for epoch in range(500):
    optimizer.zero_grad()
    outputs = model(and_data)
    loss = loss_fn(outputs, and_labels)
    print('loss', loss) #크로스 엔트로피로스라서 확률로 나온다 
    loss.backward() #미분
    optimizer.step()

loss tensor(0.5754, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5752, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5749, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5747, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5745, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5742, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5740, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5737, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5735, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5732, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5730, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5727, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5725, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5723, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5720, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5718, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.5715, grad_fn=<BinaryCrossEntropyBackward0

In [24]:
model(and_data)

tensor([[0.2338],
        [0.2809],
        [0.3953],
        [0.4557]], grad_fn=<SigmoidBackward0>)

In [25]:
# def and_gate(x1, x2):
#     return x1 and x2

In [ ]:
import numpy as np
