# 03Pandas
* csv 같은 파일을 읽어들일 때 쓴다
* export 시켜서 pandas로 메모리영역에 데이터베이스를 생성한다
* 3가지 객체가 있다
* Series, DataFrame, Index

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [13]:
import numpy as np
import pandas as pd

## Pandas Series
* 인덱싱 된 데이터의 1차원 배열
* key 값을 잃어버리지만 않으면 언제든지 사용이 가능하다
* numpy인지 pandas인지 헷갈리면 type()사용하자

In [38]:
data = pd.Series([0.25,0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [39]:
type(data.values), data.values

(numpy.ndarray, array([0.25, 0.5 , 0.75, 1.  ]))

In [40]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [41]:
data[1], type(data)

(0.5, pandas.core.series.Series)

In [44]:
len(data)
#python 사용가능

4

In [35]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### 일반화된 Numpy배열
* numpy 배열에는 값을 접근하는데 사용되는 암묵적으로 정해진 정수형 인덱스
* pandas 배열에는 값에 연결된 명시적 인덱스

In [24]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [25]:
data['b']

0.5

### Dict

In [90]:
pop_dict = {"Cal" : 38000000,
            "Tex" : 26400000,
            "Ny" : 19600000,
            "Flo": 19500000,
            "Il" : 12800000}
pop = pd.Series(pop_dict)
pop, type(pop)

(Cal    38000000
 Tex    26400000
 Ny     19600000
 Flo    19500000
 Il     12800000
 dtype: int64,
 pandas.core.series.Series)

In [71]:
pop['Cal']

38000000

In [72]:
pop['Cal':'Flo']

Cal    38000000
Tex    26400000
Ny     19600000
Flo    19500000
dtype: int64

In [73]:
pd.Series(data, index=index)

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [74]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [75]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

## Pandas DataFrame
* Pandas의 기본 구조체는 DataFrame
* exel이랑비슷함

### 일반화된 Numpy 배열

In [95]:
df_dict = {'Cal':42000, 'Tex':69000, 'Ny':14000, 'Flo':17000, 'Il':14900}
area = pd.Series(area_dict)
area

Cal    42000
Tex    69000
Ny     14000
Flo    17000
Il     14900
dtype: int64

In [78]:
states = pd.DataFrame({'pop':pop, 'area':area})
states

pop   area
Cal  38000000  42000
Tex  26400000  69000
Ny   19600000  14000
Flo  19500000  17000
Il   12800000  14900

In [79]:
states.index

Index(['Cal', 'Tex', 'Ny', 'Flo', 'Il'], dtype='object')

In [81]:
states.columns

Index(['pop', 'area'], dtype='object')

## pr1
* read_csv
* average
* info
* describe
* 데이터 읽어오고, 헤드보고, 인포보고, describe

In [104]:
df = pd.read_csv('python-ds-handbook/notebooks/data/president_heights.csv')
df.head() #head는 기본 5개

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [98]:
np.average(df['height(cm)'])

179.73809523809524

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   order       42 non-null     int64 
 1   name        42 non-null     object
 2   height(cm)  42 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 1.1+ KB


In [102]:
df.describe()

order  height(cm)
count  42.000000   42.000000
mean   22.476190  179.738095
std    13.152461    7.015869
min     1.000000  163.000000
25%    11.250000  174.250000
50%    22.000000  182.000000
75%    33.750000  183.000000
max    44.000000  193.000000

### DataFrame:speacily dict

In [82]:
states['area']

Cal    42000
Tex    69000
Ny     14000
Flo    17000
Il     14900
Name: area, dtype: int64

### DataFrame 객체 구성하기

In [83]:
pd.DataFrame(pop,columns=['pop'])

pop
Cal  38000000
Tex  26400000
Ny   19600000
Flo  19500000
Il   12800000

In [85]:
data = [{'a': i, 'b': 2*i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [87]:
pd.DataFrame([{'a':1, 'b':2},{'b':3, 'c':4}])
#딕셔너리의 일부키가 누락되더라도 NaN으로 채움

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [89]:
# DataFrame은 Series 객체의 딕셔너리로 구성이 가능
pd.DataFrame({'pop':pop, 'area':area})

pop   area
Cal  38000000  42000
Tex  26400000  69000
Ny   19600000  14000
Flo  19500000  17000
Il   12800000  14900

## Pandas Index

### Index 불변의 배열

In [107]:
idx = pd.Index([2,3,5,7,11])
idx

Index([2, 3, 5, 7, 11], dtype='int64')

In [108]:
idx[1]

3

In [109]:
idx[::2]

Index([2, 5, 11], dtype='int64')

In [110]:
print(idx.size, idx.shape, idx.ndim, idx.dtype)

5 (5,) 1 int64


In [112]:
idx[1] = 0
# Numpy와 배열과의 한가지 차이점으로 Index객체는 일반적인 방법으로 변경할 수 없는 불변의 값

TypeError: Index does not support mutable operations

### Index 정렬된 집합

In [113]:
idxA = pd.Index([1,3,5,7,9])
idxB = pd.Index([2,3,5,7,11])

In [123]:
idxA & idxB, idxA.intersection(idxB)
#교집합

(Index([0, 3, 5, 7, 9], dtype='int64'), Index([3, 5, 7], dtype='int64'))

In [124]:
idxA | idxB, idxA.union(idxB)

(Index([3, 3, 5, 7, 11], dtype='int64'),
 Index([1, 2, 3, 5, 7, 9, 11], dtype='int64'))

In [126]:
idxA ^ idxB, idxA.t(idxB)

AttributeError: 'Index' object has no attribute 'deffrent'

## Data indexing and selection

### Series에서 데이터 선택

### Series딕셔너리
* key의 집합을 값의 집합에 매핑

In [127]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [128]:
data['b']

0.5

In [129]:
'a' in data

True

In [131]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [144]:
data.values

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [148]:
d_mask = data > 0.5

In [149]:
data[d_mask]

c    0.75
d    1.00
e    1.25
dtype: float64

In [132]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [133]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series 1차원배열

In [138]:
data['a':'c'] #명시적 인덱스로 슬라이싱

a    0.25
b    0.50
c    0.75
dtype: float64

In [140]:
data[0:2] # 암묵적 정수 슬라이싱

a    0.25
b    0.50
dtype: float64

In [141]:
data[(data>0.3) & (data<0.8)] # 마스킹

b    0.50
c    0.75
dtype: float64

In [142]:
data[['a','e']] #팬시 인덱싱

a    0.25
e    1.25
dtype: float64

### 인덱서 loc, iloc

In [152]:
df = pd.read_csv('python-ds-handbook/notebooks/data/president_heights.csv' ,names=['order', 'name', 'height'])
df.head() #head는 기본 5개

order               name      height
0  order               name  height(cm)
1      1  George Washington         189
2      2         John Adams         170
3      3   Thomas Jefferson         189
4      4      James Madison         163

In [151]:
df.loc[40, 'name':'height']

name          George W. Bush
height(cm)               182
Name: 40, dtype: object

In [150]:
df.iloc[40,1:2]

name    George W. Bush
Name: 40, dtype: object

## DataFrame 에서 Data Selection

In [166]:
title_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
title_df.head() #head는 기본 5개

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [174]:
df.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [178]:
df[['Age', 'Fare']]

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [179]:
df.Age is df['Age']

True

In [185]:
df['denciy'] = df['Age'] / df['Fare']
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked    denciy  
0      0         A/5 21171   7.2500   NaN        S  3.034483  
1      0          PC 17599  71.2833   C85        C  0.533084  
2      0  STON/O2. 3101282   7.9250   NaN        S  3.280757  
3      0            113803  53.1000  C123        S  0.659134  
4      0            373450   8.0500   NaN        S  4.347826

In [188]:
type(df.denciy)

pandas.core.series.Series

In [192]:
df.values

array([[1, 0, 3, ..., nan, 'S', 3.0344827586206895],
       [2, 1, 1, ..., 'C85', 'C', 0.5330841866187452],
       [3, 1, 3, ..., nan, 'S', 3.280757097791798],
       ...,
       [889, 0, 3, ..., nan, 'S', nan],
       [890, 1, 1, ..., 'C148', 'C', 0.8666666666666667],
       [891, 0, 3, ..., nan, 'Q', 4.129032258064516]], dtype=object)

In [194]:
df.values.shape

(891, 13)

In [190]:
df_np=df.values
type(df.values),df_np.shape,df_np.T.shape

(numpy.ndarray, (891, 13), (13, 891))

In [195]:
df.T

0    \
PassengerId                        1   
Survived                           0   
Pclass                             3   
Name         Braund, Mr. Owen Harris   
Sex                             male   
Age                             22.0   
SibSp                              1   
Parch                              0   
Ticket                     A/5 21171   
Fare                            7.25   
Cabin                            NaN   
Embarked                           S   
denciy                      3.034483   

                                                           1    \
PassengerId                                                  2   
Survived                                                     1   
Pclass                                                       1   
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...   
Sex                                                     female   
Age                                                       38.0   
SibSp                                                        1   
Parch                                                        0   
Ticket                                                PC 17599   
Fare                                                   71.2833   
Cabin                                                      C85   
Embarked                                                     C   
denciy                                                0.533084   

                                2    \
PassengerId                       3   
Survived                          1   
Pclass                            3   
Name         Heikkinen, Miss. Laina   
Sex                          female   
Age                            26.0   
SibSp                             0   
Parch                             0   
Ticket             STON/O2. 3101282   
Fare                          7.925   
Cabin                           NaN   
Embarked                          S   
denciy                     3.280757   

                                                      3    \
PassengerId                                             4   
Survived                                                1   
Pclass                                                  1   
Name         Futrelle, Mrs. Jacques Heath (Lily May Peel)   
Sex                                                female   
Age                                                  35.0   
SibSp                                                   1   
Parch                                                   0   
Ticket                                             113803   
Fare                                                 53.1   
Cabin                                                C123   
Embarked                                                S   
denciy                                           0.659134   

                                  4                 5    \
PassengerId                         5                 6   
Survived                            0                 0   
Pclass                              3                 3   
Name         Allen, Mr. William Henry  Moran, Mr. James   
Sex                              male              male   
Age                              35.0               NaN   
SibSp                               0                 0   
Parch                               0                 0   
Ticket                         373450            330877   
Fare                             8.05            8.4583   
Cabin                             NaN               NaN   
Embarked                            S                 Q   
denciy                       4.347826               NaN   

                                 6                               7    \
PassengerId                        7                               8   
Survived                           0                               0   
Pclass                             1                               3   
Name         McCarthy, Mr. Tim

In [197]:
df.values[0]

array([1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0,
       'A/5 21171', 7.25, nan, 'S', 3.0344827586206895], dtype=object)

In [198]:
df.values[0:3,1:3]

array([[0, 3],
       [1, 1],
       [1, 3]], dtype=object)

In [201]:
df.iloc[0:3,1:3]

Survived  Pclass
0         0       3
1         1       1
2         1       3

In [206]:
df.loc[df.Age > 22]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
884          885         0       3   
885          886         0       3   
886          887         0       2   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
..                                                 ...     ...   ...    ...   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked    denciy  
1        0          PC 17599  71.2833   C85        C  0.533084  
2        0  STON/O2. 3101282   7.9250   NaN        S  3.280757  
3        0            113803  53.1000  C123        S  0.659134  
4        0            373450   8.0500   NaN        S  4.347826  
6        0             17463  51.8625   E46        S  1.041215  
..     ...               ...      ...   ...      ...       ...  
884      0   SOTON/OQ 392076   7.0500   NaN        S  3.546099  
885      5            382652  29.1250   NaN        Q  1.339056  
886      0            211536  13.0000   NaN        S  2.076923  
889      0            111369  30.0000  C148        C  0.866667  
890      0            370376   7.7500   NaN        Q  4.129032  

[483 rows x 13 columns]

In [209]:
df.Age > 24 , df.Age <40

(0      False
 1       True
 2       True
 3       True
 4       True
        ...  
 886     True
 887    False
 888    False
 889     True
 890     True
 Name: Age, Length: 891, dtype: bool,
 0       True
 1       True
 2       True
 3       True
 4       True
        ...  
 886     True
 887     True
 888    False
 889     True
 890     True
 Name: Age, Length: 891, dtype: bool)

In [211]:
df.loc[df.Age>30]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
6              7         0       1   
11            12         1       1   
..           ...       ...     ...   
873          874         0       3   
879          880         1       1   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare Cabin Embarked    denciy  
1        0  PC 17599  71.2833   C85        C  0.533084  
3        0    113803  53.1000  C123        S  0.659134  
4        0    373450   8.0500   NaN        S  4.347826  
6        0     17463  51.8625   E46        S  1.041215  
11       0    113783  26.5500  C103        S  2.184557  
..     ...       ...      ...   ...      ...       ...  
873      0    345765   9.0000   NaN        S  5.222222  
879      1     11767  83.1583   C50        C  0.673414  
881      0    349257   7.8958   NaN        S  4.179437  
885      5    382652  29.1250   NaN        Q  1.339056  
890      0    370376   7.7500   NaN        Q  4.129032  

[305 rows x 13 columns]

## Pandas에서 데이터 연산

In [212]:
import pandas as pd
import numpy as np

In [213]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [214]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [215]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [216]:
np.sin(df * np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

### universial 함수

In [217]:
area = pd.Series({'Al':1720000,'Tx':690000,'Ca':42000}, name='area')
pop = pd.Series({'Ca':3833000,'Tx':26440000,'Ny':19650000}, name='pop')

In [218]:
pop / area

Al          NaN
Ca    91.261905
Ny          NaN
Tx    38.318841
dtype: float64

In [221]:
area.index  pop.index

TypeError: unsupported operand type(s) for |: 'str' and 'str'

In [223]:
a = pd.Series([2,4,6], index=[0,1,2])
b = pd.Series([1,3,5], index=[1,2,3])
a+b

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [224]:
a.add(b,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### DataFrame에서 인덱스 정렬

In [233]:
a = pd.DataFrame(rng.randint(0,20,(2,2)), columns=list('AB'))
a

A   B
0   8   1
1  19  14

In [234]:
b = pd.DataFrame(rng.randint(0,10,(3,3)), columns=list('BAC'))
b

B  A  C
0  6  7  2
1  0  3  1
2  7  3  1

In [235]:
a + b

A     B   C
0  15.0   7.0 NaN
1  22.0  14.0 NaN
2   NaN   NaN NaN

In [238]:
fill = a.stack().mean()
a.add(b, fill_value=fill)

A     B     C
0  15.0   7.0  12.5
1  22.0  14.0  11.5
2  13.5  17.5  11.5

### universial 함수: DataFrame과 Series 간의 연산

In [240]:
a = rng.randint(10,size=(3,4))
a

array([[5, 5, 9, 3],
       [5, 1, 9, 1],
       [9, 3, 7, 6]])

In [241]:
a-a[0]

array([[ 0,  0,  0,  0],
       [ 0, -4,  0, -2],
       [ 4, -2, -2,  3]])

In [242]:
df = pd.DataFrame(a, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0 -4  0 -2
2  4 -2 -2  3

In [245]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0  0  0  4 -2
1  4  0  8  0
2  6  0  4  3

In [246]:
halfrow = df.iloc[0,::2]
halfrow

Q    5
S    9
Name: 0, dtype: int32

In [247]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN  0.0 NaN
2  4.0 NaN -2.0 NaN

### 누락된 데이터 처리하기

In [248]:
vals1 = np.array([1,None,2,3])
vals1

array([1, None, 2, 3], dtype=object)

In [249]:
%timeit np.arange(1E6, dtype=int).sum()

1.3 ms ± 21.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [252]:
%timeit np.arange(1E6, dtype=object).sum()

38.3 ms ± 604 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [254]:
vals1.sum()
# 파이썬은 None을 사용한 산술연산을 지원하지 않아 오류발생

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [255]:
vals2 = np.array([1,np.nan,3,4])
vals2.dtype

dtype('float64')

In [256]:
1 + np.nan

nan

In [257]:
0 * np.nan

nan

In [258]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [259]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

### Pandas에서 NaN, None

In [279]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [262]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [263]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

### Pandas의 NUllable type

In [280]:
pd.Series([1,np.nan,2,None,pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [281]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [282]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [283]:
data.dropna()

0        1
2    hello
dtype: object

In [285]:
df = pd.DataFrame([[1, np.nan, 2], [2,3,5],[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [286]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [289]:
df.dropna(axis='columns', how="all")

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [291]:
df.dropna(axis='rows', thresh=3)

0    1  2
1  2.0  3.0  5

In [292]:
df.fillna(0)

0    1  2
0  1.0  0.0  2
1  2.0  3.0  5
2  0.0  4.0  6

In [293]:
df.bfill()

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

In [294]:
tititanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
tititanic_df.head() #head는 기본 5개

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [296]:
tititanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [298]:
avg_age = np.nanmean(tititanic_df.Age.values)
new_df = tititanic_df['Age'].fillna(avg_age)

In [299]:
new_df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Age
Non-Null Count  Dtype  
--------------  -----  
891 non-null    float64
dtypes: float64(1)
memory usage: 7.1 KB


In [300]:
avg_age

29.69911764705882